version: '2'
services:
    fbpost-app:
        image: fbpost
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fbpost-mysql:3306/fbpost?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    fbpost-mysql:
        extends:
            file: mysql.yml
            service: fbpost-mysql
